version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - i2b2-net

  ## i2b2transmart stack ##
  # transmart
  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    environment:
      # debug options
      - JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    entrypoint: ./bin/catalina.sh jpda run
    restart: always
    depends_on:
      # - db
      - i2b2-wildfly
      - nginx
    networks:
      - i2b2-net
      - i2b2-hack
    expose:
      - 8080
    ports:
      # debug port
      - 8000:8000
    volumes:
      # local transmart.war directory (for simple development)
      - ${LOCAL_TRANSMART}:/usr/local/tomcat/webapps/:cached
      # required for DI-1026 i2b2-hack localhost fix -Andre
      - ./hosts/nsswitch.conf:/etc/nsswitch.conf:ro


  # i2b2-wildfly
  i2b2-wildfly:
    image: dbmi/i2b2-wildfly:${i2b2_wildfly_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    restart: always
    # depends_on:
    #   - db
    networks:
      i2b2-net:
      i2b2-hack:
          aliases:
              - localhost
    expose:
      - 9090

  # Rserve
  rserve:
    image: dbmi/rserve:${rserve_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    entrypoint: R CMD
    command: Rserve.dbg --no-save --RS-conf /etc/Rserv.conf
    expose:
      - 6311
    networks:
      - i2b2-net

  # remote database ssh tunnel
  db:
    image: thomass/ssh-client:${db_version}
    hostname: ${ORACLEHOST}
    #container_name: ${ORACLEHOST}
    env_file:
      - ${ENV_FILE}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    volumes:
      - ~/.ssh:/ssh:ro
    command: ssh -Ngv -L ${DOCKER_DB_PORT}:${ORACLEHOST}:${DB_PORT} -i /ssh/${SSH_KEY} -o StrictHostKeyChecking=no ${SSH_HOST}
    networks:
      - i2b2-net
    ports:
      - ${DOCKER_DB_PORT}:${DB_PORT}

networks:
    i2b2-net:
    i2b2-hack:
