version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443

  ## i2b2transmart stack ##
  # transmart
  transmart:
    image: dbmi/i2b2transmart:${i2b2transmart_version}
    env_file:
      - ${ENV_FILE}
    restart: always
    depends_on:
      - nginx
    expose:
      - 8080

  ## PIC-SURE API Stack ##
  # IRCT
  irct:
    image: dbmi/irct:${irct_version}
    depends_on:
         - nginx
         - db
    env_file:
         - ${ENV_FILE}
    restart: always
    expose:
         - 8080

  irct-init:
    image: dbmi/irct-init:${irct_init_version}
    depends_on:
        - irct
    env_file:
        - ${ENV_FILE}


  # IRCT DB
  db:
    image: mysql:latest
    env_file:
        - ${ENV_FILE}
    environment:
        - MYSQL_DATABASE=irct
    restart: always
    expose:
        - 3306
    ports:
        - 3306:3306
    volumes:
        - mysql-data:/var/lib/mysql


volumes:
    mysql-data:
