version: '3.3'
services:

  # nginx
  nginx:
    image: dbmi/nginx:${nginx_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    restart: always
    # application stack exposed ports
    ports:
      - 80:80
      - 443:443
    networks:
      - i2b2-net


  ## PIC-SURE API Stack ##
  # IRCT
  picsure:
    image: dbmi/picsure2:${picsure2_version}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    depends_on:
       - nginx
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      - i2b2-net
    expose:
      - 8080

networks:
    i2b2-net:

volumes:
    mysql-data:
