version: '3.3'
services:

    # TODO: ETL process not working
    # issue with ETL and Oracle DB Services
    # ETL assumes Oralce DB SID -Andre
    # etl:
    #     image: dbmi/transmart-etl:release-16.2
    #     environment:
    #         - DB_TYPE=${DB_TYPE}
    #         - DB_HOST=db
    #         - DB_PORT=1521
    #         # kettle ETL bug
    #         - DB_ORASID=/ORCLPDB1
    #         - DB_USER=pdbadmin
    #         - DB_PASSWORD=password
    #     depends_on:
    #         - db
    #     networks:
    #         - public

    schema:
        image: dbmi/transmart-data:release-16.2
        environment:
            - DB_TYPE=${DB_TYPE}
            - DB_HOST=db
            - DB_PORT=1521
            - DB_ORASVC=ORCLPDB1
            - DB_USER=pdbadmin
            - DB_PASSWORD=password
        depends_on:
            - db
        networks:
            - public

    db:
        image: dbmi/${DB_TYPE}:${DB_VERSION}
        environment:
            # used to initialize system passwords
            - DB_PASSWORD=password
        networks:
            # public network used to access DB from outside (e.g. SQLDeveloper)
            - public
        volumes:
            # TODO: eventually remove this as a volume and add it
            # to the dbmi/oracle base image -Andre
            - ./startup:/opt/oracle/scripts/startup:ro
        expose:
            - 1521
        ports:
            - 1521:1521



networks:
    public:
