version: '3.3'
services:

  # IRCT DB
  db:
    image: mysql:${db_version}
    container_name: ${IRCTMYSQLADDRESS}
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    env_file:
      - ${ENV_FILE}
    environment:
      - MYSQL_DATABASE=irct
    restart: always
    expose:
      - 3306
    networks:
      - public
    ports:
      - ${DOCKER_IRCT_DB_PORT:-3306}:3306
    volumes:
      - mysql-data:/var/lib/mysql

networks:
    public:


volumes:
    mysql-data:
