version: '3.3'
services:

  # IRCT DB
  # remote database ssh tunnel
  db:
    image: thomass/ssh-client:${db_version}
    container_name: ${IRCTMYSQLADDRESS}
    env_file:
      - ${ENV_FILE}
    environment:
      - SSH_AUTH_SOCK=/ssh-agent/ssh-agent.sock
    labels:
      - "edu.hms.harvard.dbmi.stack.name=${STACK_NAME}"
      - "edu.hms.harvard.dbmi.stack.env=${STACK_ENV}"
    volumes:
      # ssh config file throws bad owner/permissions error if we don't map it to /etc/ssh - Andre
      - ${SSH_CONFIG_LOCATION}/config:/etc/ssh/ssh_config:ro
      - ssh-agent:/ssh-agent
    entrypoint: ssh -Ngv -L ${DOCKER_IRCT_DB_PORT}:${IRCTMYSQLADDRESS}:3306 -o StrictHostKeyChecking=no -F /etc/ssh/ssh_config
    command: ${SSH_CONFIG_CONFIG}
    networks:
      - i2b2-net
    ports:
      - ${DOCKER_IRCT_DB_PORT}:${DOCKER_IRCT_DB_PORT}

networks:
    i2b2-net:
volumes:
    # ssh-agent used to skip tty response for ssh key passphrase
    # allows for local machine to forward its ssh-agent
    # see docker-images/deployments/ssh-agent - Andre
    ssh-agent:
        external: true
